services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/etc/mongo  # Correction du chemin des données MongoDB
    networks:
      - applications-network

  mongoexpress:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongoexpress
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_AUTH_USERNAME: mongo
      ME_CONFIG_MONGODB_AUTH_PASSWORD: mongo
      ME_CONFIG_SITE_BASEURL: /
    depends_on:
      - mongodb
    networks:
      - applications-network
  loki:
    image: grafana/loki:3.3.1
    container_name: loki
    ports:
      - "29100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./data/loki:/loki
      - ./configurations/loki/loki-config.yaml:/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - applications-network
    depends_on:
      - mongodb
      - grafana

  alloy:
    image: grafana/alloy:v1.6.1
    container_name: alloy
    restart: unless-stopped
    ports:
      - "29145:12345"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./configurations/alloy/config.alloy:/etc/alloy/config.alloy
      - ./data/loki:/loki
      - ../logs:/tmp/logs
    networks:
      - applications-network

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "29000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - applications-network


networks:
  applications-network:
    driver: bridge
