services:
  mongodb:
    image: mongo:5.0.4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - applications-network
    volumes:
      - ./mongodb-data:/data/db  # Correction du chemin des données MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  mongoexpress:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongoexpress
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_SITE_BASEURL=/
    depends_on:
      - mongodb
    networks:
      - applications-network

networks:
  applications-network:
    driver: bridge
